<a href="https://colab.research.google.com/github/Tverdokhliebov-Vladyslav/123/blob/main/%D0%A2%D0%B2%D0%B5%D1%80%D0%B4%D0%BE%D1%85%D0%BB%D1%94%D0%B1%D0%BE%D0%B2_%D0%BF%D1%801.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Варіант 16

# Завдання 1: Створіть одновимірний масив (вектор) з найменшими непарними числами, не менше 15, та виведіть його значення.

import numpy as np
vector = np.arange(15, 30, 2)  # 15, 17, 19, 21, 23, 25, 27, 29
print("масив:", vector)


масив: [15 17 19 21 23 25 27 29]


In [18]:
# Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями випадкових дійсних чисел від 0 до одиниці.

matrix = np.random.rand(3, 3)

print("\nМасив:\n", matrix)


Масив:
 [[0.1751334  0.43635142 0.80159509]
 [0.57459337 0.07417252 0.52286039]
 [0.69340194 0.04955206 0.47215642]]


In [20]:
# Завдання 3: Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та знайдіть мін. елемент
import numpy as np

matrix = np.random.rand(3, 3)
min = np.min(matrix)

print("\nМатриця:\n", matrix)
print(f"Мінімальний елемент: {min}")


Матриця:
 [[0.90472778 0.81358427 0.50535528]
 [0.48574413 0.94749594 0.51984415]
 [0.23899352 0.32202145 0.32229353]]
Мінімальний елемент: 0.2389935218403496


In [2]:
#Завдання 4: Створіть масив розміром 3x3, заповніть його випадковими дійсними числами вдіапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить мінімальні елементи в кожному рядку

import numpy as np

matrix = np.random.rand(3, 3)

min = np.min(matrix, axis=1)

print("Матриця:")
print(matrix)

print("Вектор мінімальних елементі:")
print(min)



Матриця:
[[0.59646265 0.67789906 0.39960081]
 [0.38705809 0.22701847 0.34950452]
 [0.51011393 0.63066592 0.09667078]]
Вектор мінімальних елементі:
[0.39960081 0.22701847 0.09667078]


In [4]:
#Завдання 5: Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілимичислами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.

import numpy as np

array1 = np.random.randint(-5, 6, 4)
array2 = np.random.randint(-5, 6, 4)

sum_result = array1 + array2
sub_result = array1 - array2
mul_result = array1 * array2

print("Перший масив:")
print(array1)

print("Другий масив:")
print(array2)

print("Сума:")
print(sum_result)

print("Різниця:")
print(sub_result)

print("Добуток:")
print(mul_result)

Перший масив:
[-5  0  1  2]
Другий масив:
[ 5 -2  1  4]
Сума:
[ 0 -2  2  6]
Різниця:
[-10   2   0  -2]
Добуток:
[-25   0   1   8]


In [7]:
#Завдання 6: Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток.
import numpy as np
matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))

dobutok = np.dot(matrix1, matrix2)

print("Добуток матриць:")
print(dobutok)

Добуток матриць:
[[ 65  74  81]
 [147 218 153]
 [ 68  88  69]]


In [12]:
#Завдання 7:Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.

import numpy as np

matrix1 = np.random.randint(1, 5, (2, 3))
matrix2 = np.random.randint(1, 5, (3, 3))

dobutok = np.dot(matrix1, matrix2)

print("Матриця 2x3:")
print(matrix1)

print("Матриця 3x3:")
print(matrix2)

print("Добуток матриць:")
print(dobutok)

Матриця 2x3:
[[4 3 3]
 [4 4 4]]
Матриця 3x3:
[[4 3 3]
 [4 1 4]
 [2 3 2]]
Добуток матриць:
[[34 24 30]
 [40 28 36]]


In [14]:
#Завдання 8: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
import numpy as np

matrix = np.random.randint(1, 13, (3, 3))
inverse = np.linalg.inv(matrix)
print("Матриця:")
print(matrix)
print("\nОбернена матриця:")
print(inverse)

Матриця:
[[ 2  5 11]
 [ 9  8  1]
 [ 8 12  3]]

Обернена матриця:
[[ 0.02905569  0.28329298 -0.20096852]
 [-0.04600484 -0.19854722  0.23486683]
 [ 0.10653753  0.03874092 -0.07021792]]


In [23]:
#Завдання 9: Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -7 до 7 та транспонуйте ї
import numpy as np

matrix = np.random.uniform(-7, 7, (4, 4))
print("Матриця:")
print (matrix)

trans = np.transpose(matrix)
print("Транспонована матриця:")
print (trans)


Матриця:
[[ 4.84236684  5.71059944  6.04076479  4.3039829 ]
 [ 6.9593578  -5.33881366 -0.17437616 -5.80307923]
 [ 1.0579803  -3.56613647  4.07359475 -3.40854475]
 [ 5.5203754   4.7834968   3.75585731  4.61027445]]
Транспонована матриця:
[[ 4.84236684  6.9593578   1.0579803   5.5203754 ]
 [ 5.71059944 -5.33881366 -3.56613647  4.7834968 ]
 [ 6.04076479 -0.17437616  4.07359475  3.75585731]
 [ 4.3039829  -5.80307923 -3.40854475  4.61027445]]


In [29]:
#Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np

matrix = np.random.rand(3, 4)
print("Матриця")
print (matrix)

vector = np.random.rand(4, 1)
print("Вектор")
print(vector)

dobutok = np.dot(matrix, vector)
print("Добуток:")
print (dobutok)

Матриця
[[0.53853341 0.54391689 0.84191477 0.56307878]
 [0.88163791 0.1136566  0.90446183 0.35949309]
 [0.83361105 0.12240441 0.82553252 0.39786769]]
Вектор
[[0.87842378]
 [0.05387937]
 [0.94991052]
 [0.49213328]]
Добуток:
[[1.57921996]
 [1.81665177]
 [1.7188448 ]]


In [33]:
#Завдання 11:Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import numpy as np

matrix = np.random.rand(2, 3)
print("Матриця 2x3:")
print(matrix)

vector = np.random.randint(1, 11, (3, 1))
print("\nВектор 3x1:")
print(vector)

dobutok = np.dot(matrix, vector)
print("\nДобуток матриці на вектор:")
print(dobutok)

Матриця 2x3:
[[0.43692208 0.39763658 0.17079734]
 [0.33386326 0.5110021  0.57984025]]

Вектор 3x1:
[[5]
 [5]
 [1]]

Добуток матриці на вектор:
[[4.34359061]
 [4.80416709]]


In [35]:
#Завдання 12: Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці (поелементне ділення).
import numpy as np

matrix1 = np.random.randint(1, 11, (9, 9))
matrix2 = np.random.randint(1, 11, (9, 9))

print("Перша матриця 9x9:")
print(matrix1)

print("\nДруга матриця 9x9:")
print(matrix2)

result = matrix2[:, 1] / matrix1[:, 1]

print("\nВідношення елементів другого стовпця другої матриці до відповідних елементів першої матриці:")
print(result)

Перша матриця 9x9:
[[ 7  3  9  4  2  6  6  8  5]
 [ 8 10  2 10  4  5  7  3  8]
 [ 1  3 10  5  8  6  3  5  9]
 [ 5  7  1  8 10  6  4  9  4]
 [ 3  1  2  8  2  4  6  9  1]
 [ 2  3 10  6  7  4  2  6  1]
 [10  5  4  2  8  9  4  7  2]
 [10 10  3 10  4  1  4  6  5]
 [10  3  2  8  8  4  7  7  9]]

Друга матриця 9x9:
[[ 3  2  5  4  2  8  1 10  7]
 [ 3  9  5  3 10  5  6  8  9]
 [10  6  2  4  7 10  3  6  9]
 [10  2  7  5  5  8  7  4  2]
 [ 6  7  7  1  3  5  1  7  2]
 [ 7  2  3  2 10  2 10  9  8]
 [ 7  2  7  1  4  8  5  5  4]
 [ 4  6  2  5  8  5  4  7  7]
 [ 1  1  4  9  6  2  7  6  8]]

Відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці:
[0.66666667 0.9        2.         0.28571429 7.         0.66666667
 0.4        0.6        0.33333333]


In [37]:
#Завдання 13: Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток їх елементів.
import numpy as np

matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))

print("Перша матриця 3x3:")
print(matrix1)

print("\nДруга матриця 3x3:")
print(matrix2)

dobutok = matrix1 * matrix2

print("\nДобуток елементів матриць поелементно:")
print(dobutok)

Перша матриця 3x3:
[[ 2  6 10]
 [ 1  1  7]
 [ 7  6  3]]

Друга матриця 3x3:
[[ 1  3  6]
 [ 9  6  3]
 [10  3  4]]

Добуток елементів матриць поелементно:
[[ 2 18 60]
 [ 9  6 21]
 [70 18 12]]


In [48]:
#Завдання 15: Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем ціле значення в кожному рядку матриці.

import numpy as np

matrix = np.random.uniform(-2, 2, (3, 3))

def find_closest_integer_row(row):
    integers = np.round(row).astype(int)
    return integers[np.argmin(np.abs(integers))]

col = np.array([find_closest_integer_row(row) for row in matrix])

print("Матриця:")
print(matrix)
print("\nВектор-стовпчик найменших за модулем цілих значень:")
print(col)



Матриця:
[[-0.08095273  1.71580048 -0.42055384]
 [ 1.67397634  1.85525392 -1.59990018]
 [ 1.6265564   0.02693172 -0.67445223]]

Вектор-стовпчик найменших за модулем цілих значень:
[0 2 0]


In [ ]:
# Висновок:
# У процесі виконання лабораторної роботи було освоєно основні операції з масивами та матрицями в NumPy, такі як створення, обробка та виконання
# математичних операцій, зокрема знаходження мінімальних елементів, добуток матриць і транспонування.